{% set name = "numpy-sugar" %}
{% set version = "1.0.41" %}
{% set sha256 = "bbf72734e9e5795ca156c62746a51be3ad4805031bbee328b663937b0805c205" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win32 or linux32 or (win64 and py27)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build-capi
    - ncephes >=1.0.37
    - numpy >=1.10
  run:
    - python
    - ncephes >=1.0.37
    - numpy >=1.10
    - scipy >=0.18.1
    - dask >=0.14

test:
  requires:
    - pytest >=3
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/limix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Missing NumPy functionalities'
  doc_url: https://numpy-sugar.readthedocs.io
  dev_url: https://github.com/limix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
