{% set name = "numpy-sugar" %}
{% set version = "1.0.35" %}
{% set sha256 = "7305e79f13c1b6d3e8508d113096a60a76d28e71a57bee16f5606eb0185e7bac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build-capi
    - ncephes >=1.0.22
    - numpy >=1.11
  run:
    - python
    - ncephes >=1.0.22
    - numpy >=1.11

test:
  requires:
    - pytest >=3
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/limix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Missing NumPy functionalities'
  doc_url: https://numpy-sugar.readthedocs.io
  dev_url: https://github.com/limix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
