{% set name = "numpy-sugar" %}
{% set version = "1.0.22" %}
{% set sha256 = "c3f7d2ddffff6b75554d2adda675f67823f9272bd767df3a96ed79a57dc8efdc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True           # [win and py<35]
  features:
    - vc14             # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build-capi
    - ncephes
    - numpy >=1.9.3
    - vc 14  # [win]
  run:
    - python
    - ncephes
    - numpy >=1.9.3

test:
  requires:
    - pytest >=3
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/glimix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Missing NumPy functionalities'
  doc_url: http://numpy-sugar.readthedocs.io
  dev_url: https://github.com/glimix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
