{% set name = "numpy_sugar" %}
{% set version = "1.0.8" %}
{% set sha256 = "21d8852f7d997dfac0cc95b378043b8cea1ced50866cd4812c60b7c53cfab046" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True           # [win and py<35]
  features:
    - vc14             # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build_capi
    - ncephes
    - cffi
    - numba
    - toolchain
    - vc 14           # [win]
  run:
    - python
    - ncephes
    - scipy
    - numpy
    - numba
    - cffi

test:
  requires:
    - pytest
    - numpy
    - scipy
    - numba
  imports:
    - numpy_sugar
  commands:
    - python -c "import numpy_sugar; numpy_sugar.test()"

about:
  home: https://github.com/glimix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Missing NumPy functionalities'
  doc_url: http://numpy-sugar.readthedocs.io
  dev_url: https://github.com/glimix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
